version: '3.8'

services:
  pagepilot:
    build: .
    container_name: pagepilot-analyzer
    volumes:
      - ./input:/app/input
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    command: python main.py
